# Generated by Django 4.1 on 2023-01-10 15:24

from django.db import migrations, models
import transcriber.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('in_progress', 'In progress'), ('transcribed', 'Transcribed'), ('failed', 'Failed')], default='uploading', max_length=11, verbose_name='Transcription status')),
                ('file', models.FileField(blank=True, null=True, upload_to=transcriber.models.get_audio_file_upload_path, verbose_name='Audio file')),
                ('file_name_original', models.CharField(max_length=256, verbose_name='Original file name')),
                ('file_name', models.CharField(max_length=256, unique=True, verbose_name='File name in S3 storage')),
                ('file_type', models.CharField(max_length=256, verbose_name='File type')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Upload time')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='Transcription result')),
                ('transcription_start', models.DateTimeField(blank=True, null=True, verbose_name='Transcription start time')),
                ('transcription_end', models.DateTimeField(blank=True, null=True, verbose_name='Transcription end time')),
                ('transcription_job_id', models.UUIDField(blank=True, null=True, verbose_name='Celery transcription job id')),
            ],
        ),
    ]
